### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by VandilFish** [VolmitSoftware/PermissionsEx#16]
[12:42:20] [pool-12-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Full error:
java.lang.NullPointerException
        at ru.tehkode.permissions.bukkit.PermissionsEx.onDisable(PermissionsEx.java:241)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:234)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267)
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
        at java.lang.Thread.run(Unknown Source)

**Comment by AvianAeternum** [comment]
This stack has zero info in it, send your permissions.yml and your configs in pastebins

**Comment by VandilFish** [comment]
Permissions.yml: https://pastebin.com/38VuCz3F
Config.yml: https://pastebin.com/bUUzNVNb

**Comment by AvianAeternum** [comment]
Thats probably your problem, however i meant just every file in your permissionsex plugin folder

**Comment by VandilFish** [comment]
i only have config.yml and permissions.yml in the PermissionsEx plugin folder??

**Comment by AvianAeternum** [comment]
ok so show me the config.yml too...

**Comment by VandilFish** [comment]
Config.yml: https://pastebin.com/bUUzNVNb

**Comment by AvianAeternum** [comment]
What version is the server, and what version of pex are you using, thats a pretty outdated config

The permissions.yml looks valid though

**Comment by VandilFish** [comment]
well i'm pretty sure that config was created by the old 1.23 version as the new 1.33.8 version wouldn't create a config

**Comment by VandilFish** [comment]
would you be able to send me a new config?

**Comment by AvianAeternum** [comment]
You just delete the config and it generates a new one

**Comment by VandilFish** [comment]
Yeah i'm aware however i restarted the server multiple times and it did not create a new one

**Comment by VandilFish** [comment]
I deleted the config and restarted the server and the config wasn't created https://pastebin.com/2CVDjFGZ heres my logs

**Comment by VandilFish** [comment]
oh and the server is version 1.15.2, using the plugins, Clearlag, EssentialsX, EssentialsXAntiBuild, EssentialsXChat, EssentialsXProtect, EssentialsXSpawn, PermissionsEx, Worldedit

**Comment by VandilFish** [comment]
i've just updated everything i could and i'm still getting the issue
https://pastebin.com/qbAg3Dks

**Comment by VandilFish** [comment]
Couldn't fix the issue as it seems to be with the plugin itself.

**Comment by AvianAeternum** [comment]
This fork of pex has not been updated for use in versions 1.13 and beyond
